-- MySQL Script generated by MySQL Workbench
-- пн, 16-гру-2019 19:10:23 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Профіль`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Профіль` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Профіль` (
  `idПрофіль` INT NOT NULL,
  `Логін` VARCHAR(40) NOT NULL,
  `Пароль` VARCHAR(40) NOT NULL,
  `Пошта` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idПрофіль`),
  UNIQUE INDEX `Логін_UNIQUE` (`Логін` ASC),
  UNIQUE INDEX `Пошта_UNIQUE` (`Пошта` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Роль`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Роль` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Роль` (
  `idРоль` INT NOT NULL,
  `name` TEXT NOT NULL,
  PRIMARY KEY (`idРоль`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Призначення`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Призначення` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Призначення` (
  `idПризначення` INT NOT NULL,
  `idРоль` INT NOT NULL,
  `idПрофіль` INT NOT NULL,
  `Призначення` TEXT(40) NOT NULL,
  PRIMARY KEY (`idПризначення`, `idПрофіль`, `idРоль`),
  INDEX `fk_Призначення_Роль1_idx` (`idРоль` ASC),
  INDEX `fk_Призначення_Профіль1_idx` (`idПрофіль` ASC),
  CONSTRAINT `fk_Призначення_Роль1`
    FOREIGN KEY (`idРоль`)
    REFERENCES `mydb`.`Роль` (`idРоль`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Призначення_Профіль1`
    FOREIGN KEY (`idПрофіль`)
    REFERENCES `mydb`.`Профіль` (`idПрофіль`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Анкета`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Анкета` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Анкета` (
  `idАнкета` INT NOT NULL,
  `idПризначення` INT NOT NULL,
  PRIMARY KEY (`idАнкета`, `idПризначення`),
  INDEX `fk_Анкета_Призначення1_idx` (`idПризначення` ASC),
  CONSTRAINT `fk_Анкета_Призначення1`
    FOREIGN KEY (`idПризначення`)
    REFERENCES `mydb`.`Призначення` (`idПризначення`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Питання`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Питання` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Питання` (
  `idПитання` INT NOT NULL,
  `Вміст` TEXT NOT NULL,
  `idАнкета` INT NOT NULL,
  PRIMARY KEY (`idПитання`, `idАнкета`),
  INDEX `fk_Питання_Анкета1_idx` (`idАнкета` ASC),
  CONSTRAINT `fk_Питання_Анкета1`
    FOREIGN KEY (`idАнкета`)
    REFERENCES `mydb`.`Анкета` (`idАнкета`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Відповідь`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Відповідь` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Відповідь` (
  `idВідповідь` INT NOT NULL,
  `Вміст` TEXT NOT NULL,
  `idПрофіль` INT NOT NULL,
  PRIMARY KEY (`idВідповідь`, `idПрофіль`),
  INDEX `fk_Відповідь_Профіль1_idx` (`idПрофіль` ASC),
  CONSTRAINT `fk_Відповідь_Профіль1`
    FOREIGN KEY (`idПрофіль`)
    REFERENCES `mydb`.`Профіль` (`idПрофіль`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Відповідь_Питання1`
    FOREIGN KEY (`idВідповідь`)
    REFERENCES `mydb`.`Питання` (`idПитання`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`State`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`State` ;

CREATE TABLE IF NOT EXISTS `mydb`.`State` (
  `idState` INT NOT NULL,
  `name` TEXT NOT NULL,
  PRIMARY KEY (`idState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Event` (
  `idEvent` INT NOT NULL,
  `date` DATE NOT NULL,
  `initiator` INT NOT NULL,
  `idАнкета` INT NOT NULL,
  PRIMARY KEY (`idEvent`, `initiator`, `idАнкета`),
  INDEX `fk_Event_Профіль1_idx` (`initiator` ASC),
  INDEX `fk_Event_Анкета1_idx` (`idАнкета` ASC),
  CONSTRAINT `fk_Event_Профіль1`
    FOREIGN KEY (`initiator`)
    REFERENCES `mydb`.`Профіль` (`idПрофіль`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_Анкета1`
    FOREIGN KEY (`idАнкета`)
    REFERENCES `mydb`.`Анкета` (`idАнкета`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_State1`
    FOREIGN KEY (`idEvent`)
    REFERENCES `mydb`.`State` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
